apiVersion: apps/v1
kind: Deployment
metadata:
  name: station-service-deployment
  labels:
    app: station-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: station-service
  template:
    metadata:
      labels:
        app: station-service
    spec:
      containers:
      - name: station-service
        image: 092356264921.dkr.ecr.eu-central-1.amazonaws.com/station-service:c30f93ef801d809d91e901c3e219ee6097fe8de6
        ports:
        - containerPort: 8080